### PR TITLE
Add twitter follow badge

### PR DESCRIPTION
**Pull request by gcochard**
This is waiting on badges/shields#545 to be merged.

### CODE REVIEW

**Comment by ryanbmilbourne** [comment]
@gcochard I closed the fluff Pull Requests that Greenkeeper had opened up.  Can you update your branch?  Should be okay to merge once the checks pass.

**Comment by ryanbmilbourne** [comment]
Once you update your branch I'll merge this.  Looks like you were able to submit your badge to the shields project as well. :+1:

**Comment by ryanbmilbourne** [comment]
PM me as soon as you catch up with the last few commits and I'll merge this.  It keeps slipping through the cracks. :cry:

**Comment by gcochard** [comment]
@ryanbmilbourne ready to go.

**Comment by ryanbmilbourne** [comment]
:shipit:

**Pull request merged**
