### PR TITLE
Add david-dm badge

### PR DESCRIPTION
**Pull request by gcochard**
This change cleans up all of the images and links in the header, as well as adds a david-dm badge to show whether our dependencies are out of date.

### CODE REVIEW

**Comment by ryanbmilbourne** [comment]
:+1:

**Comment by ryanbmilbourne** [comment]
Will merge once builds complete.  It's unfortunate that `david` and `greenkeeper` doesn't cover both PR submission and a badge.

**Comment by gcochard** [comment]
Restarted the build, since it hadn't started on any of the build agents for >1hr.

**Comment by gcochard** [comment]
Builds are suspended: https://www.traviscistatus.com/incidents/lpgbdfcmjhpk

**Comment by ryanbmilbourne** [comment]
OK.  Seeing as it's just a badge, I shall merge.

**Comment by gcochard** [comment]
```
............................................________........................ 
....................................,.-‘”...................``~.,.................. 
.............................,.-”...................................“-.,............ 
.........................,/...............................................”:,........ 
.....................,?......................................................\,..... 
.................../...........................................................,}.... 
................./......................................................,:`^`..}.... 
.............../...................................................,:”........./..... 
..............?.....__.........................................:`.........../..... 
............./__.(.....“~-,_..............................,:`........../........ 
.........../(_....”~,_........“~,_....................,:`........_/........... 
..........{.._$;_......”=,_.......“-,_.......,.-~-,},.~”;/....}........... 
...........((.....*~_.......”=-._......“;,,./`..../”............../............ 
...,,,___.\`~,......“~.,....................`.....}............../............. 
............(....`=-,,.......`........................(......;_,,-”............... 
............/.`~,......`-...............................\....../\................... 
.............\`~.*-,.....................................|,./.....\,__........... 
,,_..........}.>-._\...................................|..............`=~-,.... 
.....`=~-,_\_......`\,.................................\........................ 
...................`=~-,,.\,...............................\....................... 
................................`:,,...........................`\..............__.. 
.....................................`=-,...................,%`>--==``....... 
........................................_\..........._,-%.......`\............... 
...................................,<`.._|_,-&``................`\..............
```

**Pull request merged**
